name: Expert correctness and performance
on: {workflow_dispatch: {}}
jobs:
  swift-core-linux:
    runs-on: ubuntu-24.04
    container: swift:6.0.3-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Actual Swift core tests on Linux (not iPad)
        run: swift test -c release
